Update README
rt-net/raspimouse_sim pull request #54
Opened 2020-10-26 06:55 UTC by Tiryoh

# What does this implement/fix?

#53 で反映しきれていなかったドキュメントを修正します。
#40 についても対応しています。

# Does this close any currently open issues?

#40

# How has this been tested?

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2020-11-09 05:24 UTC, ShotaAk requested changes

2020-11-09 05:24 UTC, ShotaAk commented on README.md
> +    ```
メールアドレスを許可なくREADMEに書くのは避けたいです。

package.xmlを見れば確認できるので、リポジトリ名だけで良いと思います。

2020-11-09 05:24 UTC, ShotaAk commented on README.md
> +roslaunch raspimouse_ros_examples teleop.launch key:=true mouse:=false
`raspimouse_ros_examples`のインストール方法(git clone)の追記をお願いします

2020-11-09 05:24 UTC, ShotaAk commented on README.md
> +cd ~/catkin_ws && catkin build
`catkin`はROSインストール時に導入されないので、ここは`catkin_make`にしておきたいです。

2020-11-09 08:14 UTC, Tiryoh commented on README.md
> +    ```
メールアドレスなしでリスト化して書きます

2020-11-10 01:47 UTC, Tiryoh commented on README.md
> +    ```
https://github.com/rt-net/raspimouse_sim/pull/54/commits/9a300a42689f6874ed447921f7e521cd0f0caa46 にてリスト化しました

2020-11-10 01:48 UTC, Tiryoh commented on README.md
> +cd ~/catkin_ws && catkin build
https://github.com/rt-net/raspimouse_sim/pull/54/commits/568d429b08242fcbee1e06ec4ee73a5402ec9e03 にて差し替えました

2020-11-10 01:48 UTC, Tiryoh commented on README.md
> +roslaunch raspimouse_ros_examples teleop.launch key:=true mouse:=false
https://github.com/rt-net/raspimouse_sim/pull/54/commits/568d429b08242fcbee1e06ec4ee73a5402ec9e03 にてgit cloneからcatkin_makeまで追記しました

2020-11-10 01:49 UTC, Tiryoh commented on README.md
> +roslaunch raspimouse_ros_examples teleop.launch key:=true mouse:=false
raspimouse_ros_examples がなくても raspimouse_sim 自体は動くので補足情報扱いとしています。

2020-11-10 04:34 UTC, ShotaAk approved these changes
変更確認しました。良いと思います。

2020-11-10 04:34 UTC, merged