controller managerノードにプラグインを追加するように変更
rt-net/raspimouse_sim pull request #68
Opened 2023-09-22 09:47 UTC by YusukeKato

# What does this implement/fix?

controller managerノードにjoint_state_broadcasterとdiff_drive_controllerを追加するように変更しました。

# Does this close any currently open issues?

しません。

# How has this been tested?

下記のコマンドを実行してGazebo上のラズパイマウスが移動することを確認しました。
```sh
ros2 launch raspimouse_gazebo raspimouse_with_emptyworld.launch.py
```

トピックは`/diff_drive_controller/cmd_vel_unstamped`を指定しました。
```sh
ros2 run teleop_twist_keyboard teleop_twist_keyboard
```

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-09-25 02:10 UTC, ShotaAk commented
cmd_velトピックのネームスペースを変更しないと動作しませんでした。

```sh
ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r cmd_vel:=diff_drive_controller/cmd_vel_unstamped
```

2023-09-25 02:15 UTC, ShotaAk commented
ついでに、RVizにRobotModelとOdometryを表示してほしいです。
Odomが出力されているかデバッグするためです。
![image](https://github.com/rt-net/raspimouse_sim/assets/18494952/95548fe2-a93a-4cef-9d79-c118f9a2590b)

2023-09-25 02:24 UTC, ShotaAk requested changes
Gazebo上でRasPiMouseが動くことを確認しました。

レビューコメントの確認おねがいします。

2023-09-25 02:24 UTC, ShotaAk commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
multiplierが1.00から変更されています。
これは実機とシミュレータそれぞれを動かし、チューニングしたということですか？

2023-09-25 02:24 UTC, ShotaAk commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
例えば、1m/s の速度指示を1秒間与えたら1m進むのか、1rad/sの回転指示を1秒間与えたら1rad回転するのか確認お願いします。

おおよそ合っていればokです。

2023-09-25 02:24 UTC, ShotaAk commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    wheel_radius : 0.024
raspimouse_hardwareリポジトリなどを参考に
これらのパラメータが実機と合っているか、確認お願いします。

2023-09-29 09:35 UTC, YusukeKato commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    wheel_radius : 0.024
実機を計測して正しいことを確認しました。

2023-09-29 09:45 UTC, YusukeKato commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
下記のパラメータを設定した上で、0.5m/sの速度指示を10秒間与えたところ、走行距離は3.7mでした。この場合はどのパラメータを調整すればよいでしょうか。

```
wheel_separation : 0.09
wheels_per_side: 1
wheel_radius : 0.024
wheel_separation_multiplier : 1.0
left_wheel_radius_multiplier : 1.0
right_wheel_radius_multiplier : 1.0
```

2023-09-29 10:06 UTC, YusukeKato commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
同じパラメータで、1.0rad/sを2秒間与えたところ、回転角度は-2.4radでした。

2023-10-02 02:36 UTC, ShotaAk commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
下記コマンドでロボットの速度を観測しましたが、直進速度が0.34 m/sに制限されていました。
原因は見つかってないです。

```sh
# 速度の観測
$ ros2 topic echo /diff_drive_controller/odom --no-arr

# 走行速度指令
$  ros2 topic pub /diff_drive_controller/cmd_vel_unstamped geometry_msgs/msg/Twist "linear:
  x: 0.4
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" -r 1 -t 1
```

2023-10-02 02:59 UTC, ShotaAk commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
原因はジョイントの速度が15に制限されていることでした。適当な大きな値に変更お願いします。

https://github.com/rt-net/raspimouse_description/blob/986f583e1085502c5272610131eb522b761444a2/urdf/wheel/wheel.urdf.xacro#L12

最大直進速度 = 円周 * ジョイントの回転数
= 2 * pi * r * multiplier * joint_v_limit / 2pi
= 2 * pi * 0.024 * 0.95 * 15 / 2pi
= 0.143 * 2.387
= 0.341

2023-10-02 03:03 UTC, ShotaAk commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
gazebo上では実機よりも速度を出せるように、2.0 m/sを目指してください。

少なくとも最大速度0.34 m/sは実機より遅いです。

2023-10-03 06:29 UTC, YusukeKato commented on raspimouse_gazebo/config/raspimouse_controllers.yaml
> +    right_wheel_radius_multiplier : 0.95
ジョイントの速度制限を90に変更し、下記のパラメータでテストしました。
```
wheel_separation : 0.09
wheels_per_side: 1
wheel_radius : 0.024
wheel_separation_multiplier : 1.0
left_wheel_radius_multiplier : 1.0
right_wheel_radius_multiplier : 1.0
```
- 0.5m/sを10秒間与えたところ、走行距離は5.2mでした。
- 2.0m/sを10秒間与えたところ、走行距離は21.7mでした。
- 1.0rad/sを2秒間与えたところ、回転角度は2.0radでした。

2023-10-05 04:09 UTC, ShotaAk approved these changes
LGTM

2023-10-05 04:09 UTC, merged