シミュレータ環境に擬似的なラズパイマウスノードを追加
rt-net/raspimouse_sim pull request #69
Opened 2023-10-11 06:38 UTC by YusukeKato

# What does this implement/fix?

# Does this close any currently open issues?

# How has this been tested?

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-10-11 08:52 UTC, YusukeKato commented
lifecycle_node_manager.cppを削除したので、概要文を修正しました。

2023-10-12 11:44 UTC, ShotaAk requested changes
実装内容は良いと思います。

細かいコメントをしたので対応お願いします。

2023-10-12 11:44 UTC, ShotaAk commented on raspimouse_fake/CMakeLists.txt
> +ament_export_dependencies(rclcpp_lifecycle)
std_srvsも追加してください

```suggestion
ament_export_dependencies(rclcpp_lifecycle)
ament_export_dependencies(std_srvs)
```

2023-10-12 11:44 UTC, ShotaAk commented on raspimouse_fake/CMakeLists.txt
lifecycle_msgs も使用しているので、find_packgeやdepend等を追加してください。

2023-10-12 11:44 UTC, ShotaAk commented on raspimouse_fake/package.xml
lifecycle_msgsも追加してください

2023-10-16 01:27 UTC, ShotaAk approved these changes
LGTM

2023-10-16 01:27 UTC, merged