ライントレース用のコースを作成
rt-net/raspimouse_sim pull request #74
Opened 2023-11-15 07:17 UTC by YusukeKato

# What does this implement/fix?

ライントレース用コースのワールドを作成しました。

# Does this close any currently open issues?

しません。

# How has this been tested?

下記のコマンドを実行するとライントレース用サンプルコースのワールドが表示されます。また、RGBカメラを搭載したRaspberry Pi Mouseも配置されます。

```sh
ros2 launch raspimouse_gazebo raspimouse_with_line_follower_field.launch.py use_rgb_camera:=true
```

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-11-16 02:26 UTC, ShotaAk requested changes
コメントしました。
拡張性が高いサンプルなので今のうちに準備しておきたいです。対応お願いします。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/worlds/line_follower_world.sdf
> +      <max_step_size>0.001</max_step_size>
シミュレーション速度が50%を切ることがあるので、動作周期を小さくしてください。

```suggestion
    <physics name="10ms" type="ignored">
      <max_step_size>0.010</max_step_size>
```

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/worlds/line_follower_world.sdf
> +      <max_step_size>0.001</max_step_size>
他のworldファイルも変更したほうがようです。これは別PRで対応お願いします。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/launch/raspimouse_with_line_follower_field.launch.py
> +            '/launch/raspimouse_with_emptyworld.launch.py']),
ラズパイマウスをspawnする位置を変更できるように、emptyworld.launch.pyに引数を追加してください。
参考情報：https://github.com/rt-net/crane_x7_ros/blob/deaa39a9c821b975b450597d62471c5d8f054c93/crane_x7_gazebo/launch/crane_x7_with_table.launch.py#L50

まずは、回転なし、位置のみ（x, y, z）でお願いします。

line_follower_filed.launch.pyには引数無くてokです。

例：
```python
    world_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([
            get_package_share_directory('raspimouse_gazebo'),
            '/launch/raspimouse_with_emptyworld.launch.py']),
        launch_arguments={
            'world_name': world_file,
            'spawn_x': 0.0
            'spawn_y': 0.0
            'spawn_z': 0.1
            }.items()
    )
```

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/launch/raspimouse_with_line_follower_field.launch.py
> +            '/launch/raspimouse_with_emptyworld.launch.py']),
ライントレースフィールドをいじり始めると、ロボットの初期位置を変えたくなるので。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/model.config
> +    <email>kuwagata@rt-net.jp</email>
名前変更お願いします

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/meshes/course_curve.dae
> +      <author>Blender User</author>
AuthorはKatoさんの名前を入れてください。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/meshes/course_curve.dae
> +      <authoring_tool>Blender 2.92.0 commit date:2021-02-24, commit time:16:25, hash:02948a2cab44</authoring_tool>
blender 4.0がリリースされたのでそれで編集してください。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/model.config
パネルの寸法がわかるように、course_curve_50x50cm のような名称にしてください。

フォルダ名等も合わせて変更お願いします。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/model.sdf
> +            <scale>0.5 0.5 0.5</scale>
scaleを使用しないようにもとのdaeファイルを編集してください。

ライン幅が何cmなのかが分かりにくいためです。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/meshes/course_curve.dae
> +      <author>Blender User</author>
直線のデータも同様にお願いします。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/meshes/course_curve.jpg
パネルのサイズ、黒線の太さに付いてREADMEに説明を記載してください。

このjpg画像をREADMEに貼ると説明しやすいと思います。


例：

## モデルデータ一覧

### cource_curve_50x50cm

ライントレース用の曲線コースパネルです。
パネルサイズは50cm x 50cm、直線幅は 〇〇cmです

(ここに画像）

### cube**

それぞれ、一辺5cm、7.5cm、10cm、15cmの立方体です

（ここにスクショ）

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/worlds/line_follower_world.sdf
コースを増やす可能性が高いのでファイル名を柔軟にしたいです。

line_follower_field1.sdf にファイル名変更お願いします

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/launch/raspimouse_with_line_follower_field.launch.py
> +        'line_follower_world.sdf')
ファイル名を`line_follower_field1.sdf`に変更お願いします。

将来的には`field`のような変数を用意して、
`**launch.py field:=2` のようにフィールドを切り替えたいです。

2023-11-16 02:26 UTC, ShotaAk commented on raspimouse_gazebo/models/course_curve/meshes/course_curve.jpg
daeファイルはBlender 4.0で編集しています。のような補足も入れてほしいです。

2023-11-16 07:33 UTC, YusukeKato commented
ライントレース用コースの線幅を4cmに変更しました。

2023-11-17 02:11 UTC, ShotaAk approved these changes
LGTMです。

2023-11-17 02:11 UTC, merged